In [7]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# 1. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [8]:
(2 ** ( np.arange(1, 21) )) / np.arange(1, 21)

array([2.00000000e+00, 2.00000000e+00, 2.66666667e+00, 4.00000000e+00,
       6.40000000e+00, 1.06666667e+01, 1.82857143e+01, 3.20000000e+01,
       5.68888889e+01, 1.02400000e+02, 1.86181818e+02, 3.41333333e+02,
       6.30153846e+02, 1.17028571e+03, 2.18453333e+03, 4.09600000e+03,
       7.71011765e+03, 1.45635556e+04, 2.75941053e+04, 5.24288000e+04])

**2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [9]:
np.dot( 0.1 ** (3 * ( np.arange(6) )), 0.2 ** ( 4 * ( np.arange(6) )))

1.00000160000256

**3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [10]:
table = np.ones((8, 8))
table [1::2, 1::2] = 0
table[::2, ::2] = 0
table

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

**4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [11]:
X = np.random.random((5, 2))
X = np.concatenate((np.sqrt(X[:, 0] ** 2 + X[:, 1] ** 2),np.arctan2(X[:, 1], X[:, 0])))
X

array([1.29705889, 0.84331073, 0.83190089, 0.53464269, 0.14751296,
       0.80369681, 1.54206662, 0.88421783, 0.6758085 , 0.6640942 ])

**5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [12]:
X = np.random.random((5, 5))

np.unravel_index(np.argmax(X, axis = None), X.shape)

(3, 0)

**6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [13]:
X = np.random.random((10, 2))
y = np.random.random((1, 2))
dis = np.sqrt(np.matmul(X, np.transpose( y )))
(X[np.argmin(dis, axis=None), :])

array([0.05766517, 0.0835438 ])

**7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [14]:
x = np.linspace(-3, 3, 20)
((x ** 2 + 2 * x + 6 ) * (x < 0) + (x + 6) * ( (x >= 0) & (x <=2) ) + (x ** 2 + 4 * x - 4) * (x > 2)) 

array([ 9.        ,  7.8365651 ,  6.87257618,  6.10803324,  5.54293629,
        5.17728532,  5.01108033,  5.04432133,  5.27700831,  5.70914127,
        6.15789474,  6.47368421,  6.78947368,  7.10526316,  7.42105263,
        7.73684211,  8.42382271, 11.08310249, 13.94182825, 17.        ])

**8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [15]:
X = np.random.random(( 10, 10 ))
X = X - np.mean(X, axis=1).reshape(10, 1)
np.mean(X, axis = 1)

array([-6.66133815e-17,  7.77156117e-17,  1.22124533e-16,  0.00000000e+00,
        0.00000000e+00,  1.22124533e-16, -5.55111512e-17, -7.77156117e-17,
        4.44089210e-17,  5.55111512e-17])

**9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [16]:
X = np.random.normal(loc = 5, scale = 2. , size = 1000)
va = np.var(X)
me = np.mean(X)
(va , me)

(3.9111998688526493, 5.00123540090843)

**10.** Создать матрицу:

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [17]:
(np.arange(5) + np.arange(5).reshape(5, 1)) % 5

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 0],
       [2, 3, 4, 0, 1],
       [3, 4, 0, 1, 2],
       [4, 0, 1, 2, 3]], dtype=int32)

**11.** Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [18]:
def sample(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    res = []
    for _ in range(c):
        val = s * np.random.random()
        cur, idx = 0, 0        
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1
            
        res.append(idx)
    return res

a = [50, 3, 1, 7, 20]
b = 5            
sample(a, b)    

[0, 4, 4, 0, 0]

Реализуйте данный алгоритм более оптимальным способом, без использования циклов.

In [19]:
np.random.choice(len(a), b, p= a / np.sum(a))

array([0, 0, 0, 0, 0])